import { readFileSync, writeFileSync } from "fs";

const fixtures = JSON.parse(readFileSync("fixtures.json", "utf8"));

function hexToByteArrayLiteral(hex) {
  const bytes = [];
  for (let i = 0; i < hex.length; i += 2) {
    bytes.push("0x" + hex.slice(i, i + 2));
  }
  return "b\"" + bytes.map(b => "\\x" + b.slice(2)).join("") + "\"";
}

// MoonBit byte-string literal: b"\xHH\xHH..."
function hexToMoonbitBytes(hex) {
  let out = 'b"';
  for (let i = 0; i < hex.length; i += 2) {
    out += "\\x" + hex.slice(i, i + 2);
  }
  out += '"';
  return out;
}

function valuesArrayLiteral(values) {
  return "[" + values.map(v => v + "U").join(", ") + "]";
}

let out = `// Golden cross-language fixtures generated from roaring-wasm, a
// third-party CRoaring WASM port. Regenerate via:
//   cd tools/crossref-fixtures && npm install && npm run generate
// then run \`moon fmt\` (the generator emits unformatted long literals).
// These verify byte-for-byte compatibility with real CRoaring output, not
// just internal round-trip consistency.

`;

for (const [name, f] of Object.entries(fixtures)) {
  const testName = `golden fixture: ${name} matches CRoaring bytes`;
  out += `test "${testName}" {\n`;
  out += `  let values : Array[UInt] = ${valuesArrayLiteral(f.values)}\n`;
  out += `  let expected_bytes : Bytes = ${hexToMoonbitBytes(f.hex)}\n`;
  out += `  let bm = RoaringBitmap::from_array(values)\n`;
  out += `  assert_eq(bm.size(), ${f.size})\n`;
  out += `  let actual_bytes = bm.serialize()\n`;
  out += `  assert_eq(actual_bytes, expected_bytes)\n`;
  out += `  // Also verify MoonBit can deserialize CRoaring's own bytes.\n`;
  out += `  let restored = match RoaringBitmap::deserialize(expected_bytes) {\n`;
  out += `    Ok(r) => r\n`;
  out += `    Err(_) => fail("expected successful deserialize of CRoaring-generated bytes")\n`;
  out += `  }\n`;
  out += `  assert_true(restored.equals(bm))\n`;
  out += `}\n\n`;
}

// Two levels up: this script lives in tools/crossref-fixtures/, the test
// file belongs in the project root alongside the other _test.mbt files.
writeFileSync("../../golden_fixtures_test.mbt", out);
console.log("Wrote ../../golden_fixtures_test.mbt (" + out.length + " bytes)");
