import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = [
  {
    name: "without runs",
    file: "bitmapwithoutruns.bin",
    sha256: "d719ae2e0150a362ef7cf51c361527585891f01460b1a92bcfb6a7257282a442",
  },
  {
    name: "with runs",
    file: "bitmapwithruns.bin",
    sha256: "1f1909bfdd354fa2f0694fe88b8076833ca5383ad9fc3f68f2709c84a2ab70e3",
  },
];

function moonBytes(buffer) {
  const chunks = [];
  for (let offset = 0; offset < buffer.length; offset += 1024) {
    const chunk = buffer.subarray(offset, offset + 1024);
    chunks.push(`b"${[...chunk].map((byte) => `\\x${byte.toString(16).padStart(2, "0")}`).join("")}"`);
  }
  return chunks.join(" +\n    ");
}

let output = `// Generated by tools/official-fixtures/generate.mjs from the two
// minimum conformance files in RoaringBitmap/RoaringFormatSpec/testdata.
// Do not edit this file by hand.

///|
fn official_fixture_is_valid(data : Bytes) -> Bool {
  match RoaringBitmap::deserialize(data) {
    Err(_) => false
    Ok(bitmap) => {
      if bitmap.size() != 200100 {
        return false
      }
      for value in [0U, 99000U, 300000U, 599997U, 700000U, 799999U] {
        if !bitmap.contains(value) {
          return false
        }
      }
      for value in [100000U, 299999U, 600000U, 699999U, 800000U] {
        if bitmap.contains(value) {
          return false
        }
      }
      // Re-serializing preserves the exact official layout and bytes.
      bitmap.serialize() == data
    }
  }
}

`;

for (const fixture of fixtures) {
  const path = join(here, "testdata", fixture.file);
  const bytes = readFileSync(path);
  const actualHash = createHash("sha256").update(bytes).digest("hex");
  if (actualHash !== fixture.sha256) {
    throw new Error(`${fixture.file}: SHA-256 mismatch: ${actualHash}`);
  }
  output += `///|\ntest "official RoaringFormatSpec fixture: ${fixture.name}" {\n`;
  output += `  assert_true(official_fixture_is_valid(\n    ${moonBytes(bytes)},\n  ))\n`;
  output += `}\n\n`;
}

const outputPath = join(here, "..", "..", "official_format_test.mbt");
writeFileSync(outputPath, output);
console.log(`Wrote ${outputPath} (${output.length} bytes)`);
